version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    environment:
      - MONGO_URI=mongodb://localhost:27017 # Connection string for MongoDB
      # - S3_BUCKET=your-s3-bucket-name               # Add this, if need to use S3
      #- AWS_ACCESS_KEY_ID=your-access-key            # Add this, if need to use S3
      #- AWS_SECRET_ACCESS_KEY=your-secret-key        # Add this, if need to use S3
      - UPLOAD_PATH=./uploads
      - TRANSCODE_PATH=./output
      - WP_COUNT=2
      - DB_NAME=hls_media
    depends_on:
      - mongo
    # volumes:
    #   - ./web/static:/app/static  # Optional: if you want to mount static files from the host
  mongo:
    image: mongo:5.0  # Use an appropriate version of MongoDB
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

  # Optional: Add another service if required (e.g., Redis, S3 Minio for testing)
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"

volumes:
  mongo-data:
